# Generated by Django 4.2.9 on 2024-09-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/')),
            ],
        ),
        migrations.CreateModel(
            name='TravelPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('review_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('reviews_count', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='packages/')),
                ('activities', models.ManyToManyField(related_name='travel_packages', to='homepage.activity')),
            ],
        ),
    ]
