# Generated by Django 4.2.9 on 2024-09-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_travelpackage_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelpackage',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='travel_packages', to='homepage.activity'),
        ),
    ]
