# Generated by Django 4.2.9 on 2024-09-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_travelpackage_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelpackage',
            name='image',
            field=models.ImageField(upload_to='packages/'),
        ),
    ]
