# Generated by Django 4.2.9 on 2024-09-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_travelpackage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='days',
            field=models.IntegerField(default=0),
        ),
    ]
