# Generated by Django 4.2.9 on 2024-09-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_travelpackage_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='actual_price',
            field=models.IntegerField(default=0),
        ),
    ]
