# Generated by Django 4.2.9 on 2024-09-13 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_travelpackage_actual_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelpackage',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
