# Generated by Django 4.2.9 on 2024-09-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_travelitinerary_itineraryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
